/**
 * VitePress scaffolding — creates .vitepress/config.ts and package.json in output dir.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SIDEBAR_PLACEHOLDER = "/* __SIDEBAR_PLACEHOLDER__ */";

function buildVitePressConfig(projectName: string): string {
  return `import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid(
  defineConfig({
    title: ${JSON.stringify(projectName)},
    description: "Generated by DeepLens",
    themeConfig: {
      sidebar: ${SIDEBAR_PLACEHOLDER},
      nav: [{ text: "Home", link: "/" }],
    },
  }),
);
`;
}

function buildPackageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: `${projectName}-docs`,
      private: true,
      scripts: {
        "dev": "vitepress dev",
        "build": "vitepress build",
        "preview": "vitepress preview",
      },
      devDependencies: {
        "vitepress": "^1.6.3",
        "vitepress-plugin-mermaid": "^2.0.17",
      },
    },
    null,
    2,
  );
}

export async function scaffoldVitePress(
  outputDir: string,
  projectName: string,
): Promise<void> {
  const vitepressDir = path.join(outputDir, ".vitepress");
  await mkdir(vitepressDir, { recursive: true });

  await writeFile(
    path.join(vitepressDir, "config.ts"),
    buildVitePressConfig(projectName),
    "utf-8",
  );

  await writeFile(
    path.join(outputDir, "package.json"),
    buildPackageJson(projectName),
    "utf-8",
  );
}

export { SIDEBAR_PLACEHOLDER };
